<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!doctype html>
<html class="light" lang="zh-CN">
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>现代书库 - 订单管理</title><%@ include file="../common/tailwind.jspf" %></head>
<body class="flex h-screen overflow-hidden antialiased font-body-md text-body-md bg-background text-on-surface">
<aside class="bg-surface-container-low h-screen w-64 flex flex-col border-r border-outline-variant fixed left-0 top-0 z-40"><div class="p-6 border-b border-outline-variant flex items-center gap-4"><div class="w-10 h-10 rounded-full bg-surface-container-high flex items-center justify-center"><span class="material-symbols-outlined text-on-surface-variant">library_books</span></div><div><h1 class="font-headline-md text-headline-md font-bold text-primary">现代书库</h1><p class="font-label-sm text-label-sm text-on-surface-variant">后台管理系统</p></div></div><nav class="flex-1 overflow-y-auto py-2"><a class="flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-surface-container" href="${pageContext.request.contextPath}/admin/dashboard"><span class="material-symbols-outlined">dashboard</span>仪表盘</a><a class="flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-surface-container" href="${pageContext.request.contextPath}/admin/books"><span class="material-symbols-outlined">menu_book</span>图书管理</a><a class="flex items-center gap-3 px-4 py-3 text-secondary bg-surface-bright font-bold border-r-4 border-secondary" href="${pageContext.request.contextPath}/admin/orders"><span class="material-symbols-outlined">receipt_long</span>订单管理</a><a class="flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-surface-container" href="${pageContext.request.contextPath}/admin/users"><span class="material-symbols-outlined">group</span>用户管理</a></nav><div class="border-t border-outline-variant p-4"><a class="flex items-center gap-3 px-4 py-2 text-on-surface-variant hover:bg-surface-container rounded-md" href="${pageContext.request.contextPath}/logout"><span class="material-symbols-outlined text-[20px]">logout</span>退出登录</a></div></aside>
<main class="flex-1 flex flex-col ml-64 bg-surface"><div class="flex-1 overflow-y-auto p-gutter-desktop"><div class="mb-8 flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><h2 class="font-headline-lg text-headline-lg font-bold text-on-surface">订单管理</h2><p class="font-body-md text-body-md text-on-surface-variant mt-2">查看和管理所有的商店订单记录，跟踪配送状态与支付进度。</p></div></div>
    <div class="bg-surface-container-lowest rounded-xl border border-outline-variant overflow-hidden flex flex-col"><div class="p-4 border-b border-outline-variant bg-surface-container-lowest flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div class="flex items-center gap-2 overflow-x-auto"><a class="px-4 py-1.5 rounded-full font-label-md text-label-md ${empty status ? 'bg-primary-container text-on-primary' : 'bg-surface-container-low text-on-surface-variant'}" href="${pageContext.request.contextPath}/admin/orders">全部</a><a class="px-4 py-1.5 rounded-full font-label-md text-label-md bg-surface-container-low text-on-surface-variant" href="${pageContext.request.contextPath}/admin/orders?status=SUBMITTED">已提交</a><a class="px-4 py-1.5 rounded-full font-label-md text-label-md bg-surface-container-low text-on-surface-variant" href="${pageContext.request.contextPath}/admin/orders?status=COMPLETED">已完成</a><a class="px-4 py-1.5 rounded-full font-label-md text-label-md bg-surface-container-low text-on-surface-variant" href="${pageContext.request.contextPath}/admin/orders?status=CANCELLED">已取消</a></div><form class="relative w-full lg:w-64" method="get" action="${pageContext.request.contextPath}/admin/orders"><span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-[20px]">search</span><input name="keyword" class="w-full pl-10 pr-4 py-2 bg-surface-container-lowest border border-outline-variant rounded-lg" placeholder="搜索订单号或用户..." type="text"/></form></div>
        <div class="overflow-x-auto"><table class="w-full text-left border-collapse"><thead><tr class="bg-surface-container-low border-b border-outline-variant"><th class="py-3 px-4 font-label-sm text-label-sm text-on-surface-variant uppercase">订单号</th><th class="py-3 px-4 font-label-sm text-label-sm text-on-surface-variant uppercase">用户</th><th class="py-3 px-4 font-label-sm text-label-sm text-on-surface-variant uppercase">下单时间</th><th class="py-3 px-4 font-label-sm text-label-sm text-on-surface-variant uppercase text-right">金额</th><th class="py-3 px-4 font-label-sm text-label-sm text-on-surface-variant uppercase">状态</th><th class="py-3 px-4 font-label-sm text-label-sm text-on-surface-variant uppercase">明细</th><th class="py-3 px-4 font-label-sm text-label-sm text-on-surface-variant uppercase text-right">操作</th></tr></thead><tbody class="divide-y divide-outline-variant"><c:forEach items="${orders}" var="order"><tr class="hover:bg-surface-container-lowest/50"><td class="py-4 px-4 whitespace-nowrap font-label-md text-label-md text-primary">${order.orderNo}</td><td class="py-4 px-4">${order.user.username}</td><td class="py-4 px-4 text-on-surface-variant"><fmt:formatDate value="${order.createTime}" pattern="yyyy-MM-dd HH:mm"/></td><td class="py-4 px-4 text-right font-label-md">￥<fmt:formatNumber value="${order.totalAmount}" pattern="0.00"/></td><td class="py-4 px-4"><span class="inline-flex items-center px-2.5 py-0.5 rounded-full font-label-sm text-label-sm bg-secondary-fixed text-on-secondary-fixed-variant">${order.status}</span></td><td class="py-4 px-4 text-on-surface-variant"><c:forEach items="${order.items}" var="item"><div>${item.bookTitle} × ${item.quantity}</div></c:forEach></td><td class="py-4 px-4 text-right"><form class="flex justify-end gap-2" method="post" action="${pageContext.request.contextPath}/admin/orders/status"><input type="hidden" name="id" value="${order.id}"/><select class="rounded-lg border-outline-variant text-sm" name="status"><option value="SUBMITTED">已提交</option><option value="COMPLETED">已完成</option><option value="CANCELLED">已取消</option></select><button class="font-label-md text-label-md text-secondary" type="submit">更新</button></form></td></tr></c:forEach></tbody></table></div>
    </div>
</div></main>
</body>
</html>
