<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!doctype html>
<html lang="zh-CN">
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>用户管理 - 现代书库</title><%@ include file="../common/tailwind.jspf" %></head>
<body class="bg-background text-on-surface min-h-screen flex">
<aside class="fixed left-0 top-0 h-full z-40 bg-surface-container-low w-64 flex flex-col border-r border-outline-variant"><div class="p-6"><h1 class="font-headline-md text-headline-md font-bold text-primary">现代书库</h1><p class="font-label-sm text-label-sm text-on-surface-variant mt-1">后台管理系统</p></div><nav class="flex-1 font-label-md text-label-md"><a class="flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-surface-container" href="${pageContext.request.contextPath}/admin/dashboard"><span class="material-symbols-outlined">dashboard</span>仪表盘</a><a class="flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-surface-container" href="${pageContext.request.contextPath}/admin/books"><span class="material-symbols-outlined">menu_book</span>图书管理</a><a class="flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-surface-container" href="${pageContext.request.contextPath}/admin/orders"><span class="material-symbols-outlined">receipt_long</span>订单管理</a><a class="flex items-center gap-3 px-4 py-3 text-secondary bg-surface-bright font-bold border-r-4 border-secondary" href="${pageContext.request.contextPath}/admin/users"><span class="material-symbols-outlined">group</span>用户管理</a></nav><div class="p-4 border-t border-outline-variant"><a class="flex items-center gap-3 px-4 py-3 text-on-surface-variant hover:bg-surface-container" href="${pageContext.request.contextPath}/logout"><span class="material-symbols-outlined">logout</span>退出登录</a></div></aside>
<main class="flex-1 ml-64 flex flex-col min-h-screen"><header class="h-16 flex items-center px-8 bg-surface border-b border-outline-variant justify-between"><div class="text-on-surface-variant font-label-md text-label-md">系统管理员 / <span class="text-primary font-bold">用户管理</span></div></header><div class="p-8 flex-1"><div class="max-w-container-max mx-auto"><div class="flex justify-between items-end mb-8"><div><h2 class="font-headline-lg text-headline-lg text-primary">用户管理</h2><p class="font-body-md text-body-md text-on-surface-variant mt-2">管理系统内的所有注册用户、角色和账户状态。</p></div></div><div class="bg-surface-container-lowest rounded-xl border border-outline-variant overflow-hidden"><table class="w-full text-left border-collapse"><thead><tr class="bg-surface-container-low border-b border-outline-variant"><th class="py-3 px-6 font-label-sm text-label-sm text-on-surface-variant uppercase">用户 ID</th><th class="py-3 px-6 font-label-sm text-label-sm text-on-surface-variant uppercase">用户</th><th class="py-3 px-6 font-label-sm text-label-sm text-on-surface-variant uppercase">邮箱</th><th class="py-3 px-6 font-label-sm text-label-sm text-on-surface-variant uppercase">注册日期</th><th class="py-3 px-6 font-label-sm text-label-sm text-on-surface-variant uppercase">角色</th><th class="py-3 px-6 font-label-sm text-label-sm text-on-surface-variant uppercase">状态</th></tr></thead><tbody class="font-body-md text-body-md"><c:forEach items="${users}" var="user"><tr class="border-b border-outline-variant hover:bg-surface"><td class="py-4 px-6 text-on-surface-variant">#USR-${user.id}</td><td class="py-4 px-6 flex items-center gap-3"><div class="w-8 h-8 rounded-full bg-primary-fixed flex items-center justify-center text-primary font-label-md text-label-md font-bold">${user.username.substring(0,1).toUpperCase()}</div><span class="font-label-md text-label-md font-bold text-primary">${user.realName}</span></td><td class="py-4 px-6">${user.email}</td><td class="py-4 px-6 text-on-surface-variant"><fmt:formatDate value="${user.createTime}" pattern="yyyy-MM-dd"/></td><td class="py-4 px-6"><span class="inline-flex items-center px-2 py-1 rounded bg-surface-container-high text-primary font-label-sm text-label-sm">${user.role}</span></td><td class="py-4 px-6"><span class="${user.status == 'ENABLED' ? 'text-on-tertiary-fixed-variant' : 'text-error'} font-label-md text-label-md">${user.status}</span></td></tr></c:forEach></tbody></table></div></div></div></main>
</body>
</html>
